#spring:
#  datasource:
#    url: jdbc:mariadb://127.0.0.1:3306/erupt_202209?characterEncoding=utf-8&autoReconnect=true&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
#    username: erupt
#    password: 1qaz2wsx
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    database-platform: org.hibernate.dialect.MariaDB103Dialect
#    database: mysql
#    hibernate:
#      ddl-auto: none
spring:
  datasource:
    url: jdbc:h2:file:./db/erupt;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # for h2 database, because erupt use h2 reserved words as column.
        globally_quoted_identifiers: true
    init:
      platform: h2